# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Cosmonaut.destroy_all
Mission.destroy_all
#CosmonautMission.destroy_all
ag = Cosmonaut.create(first_name: "Ahmed", last_name: "Gaberov", died_in_space: 1, picture: "https://miro.medium.com/fit/c/256/256/2*HTTfSN0OfLCRJmxp4KEVRA.jpeg")
yg = Cosmonaut.create(first_name: "Yuri", last_name: "Gagarin", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Gagarin_in_Sweden.jpg")
nb = Cosmonaut.create(first_name: "Nikolai", last_name: "Budarin", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Budarin%2C_Nikolai_M.jpg/800px-Budarin%2C_Nikolai_M.jpg")
vd = Cosmonaut.create(first_name: "Vladimir", last_name: "Dezhurov", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Vladimir_Dezhurov.jpg/800px-Vladimir_Dezhurov.jpg")
ak = Cosmonaut.create(first_name: "Aleksandr", last_name: "Kaleri", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Alexander_Kaleri_NASA_portrait.jpg/800px-Alexander_Kaleri_NASA_portrait.jpg")
sk = Cosmonaut.create(first_name: "Sergei", last_name: "Krikalev", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Sergei_Konstantinovich_Krikalev.jpg/800px-Sergei_Konstantinovich_Krikalev.jpg")
al = Cosmonaut.create(first_name: "Alexei", last_name: "Leonov", died_in_space: 0, picture: "https://cdn.mos.cms.futurecdn.net/ENsNr7v54E9y5j79NLYXSD-1200-80.jpg")
yl = Cosmonaut.create(first_name: "Yury", last_name: "Lonchakov", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Yuri_Lonchakov.jpg")
gp = Cosmonaut.create(first_name: "Gennady", last_name: "Padalka", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Padalka.jpg/800px-Padalka.jpg")
lp = Cosmonaut.create(first_name: "Leonid", last_name: "Popov", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Leonid_Popov.jpg/220px-Leonid_Popov.jpg")
ss = Cosmonaut.create(first_name: "Svetlana", last_name: "Savitskaya", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Svetlana_Savitskaya%2C_7_December_2018.jpg/220px-Svetlana_Savitskaya%2C_7_December_2018.jpg")
as = Cosmonaut.create(first_name: "Aleksandr", last_name: "Serebrov", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Aleksandr_Aleksandrovich_Serebrov.jpg/220px-Aleksandr_Aleksandrovich_Serebrov.jpg")
vt = Cosmonaut.create(first_name: "Valentina", last_name: "Tereshkova", died_in_space: 0, picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Valentina_Tereshkova_%282017-03-06%29.jpg/220px-Valentina_Tereshkova_%282017-03-06%29.jpg")
l = Cosmonaut.create(first_name: "Laika", last_name: nil, died_in_space: 1, picture: "https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Laika_%28Soviet_dog%29.jpg/220px-Laika_%28Soviet_dog%29.jpg")
vk = Cosmonaut.create(first_name: "Vladimir", last_name: "Komarov", died_in_space: 1, picture: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Vladimir_Mikhailovich_Komarov_photo_portrait.jpg/220px-Vladimir_Mikhailovich_Komarov_photo_portrait.jpg")

m01 = Mission.create(name: "Expedition 1 (Soyuz TM-31, STS-102)", spacecraft: "International Space Station", duration: "140 days, 23 hours, 38 minutes", orbits: nil, start_date: "November 2, 2000")
m02 = Mission.create(name: "Expedition 11 (Soyuz TMA-6)", spacecraft: "International Space Station", duration: "179 days, 23 minutes", orbits: 2817, start_date: "April 17, 2005")
m03 = Mission.create(name: "Expedition 3", spacecraft: "International Space Station", duration: "128 days, 20 hours, 45 minutes, 58 seconds", orbits: 2020, start_date: "August 12, 2001")
m04 = Mission.create(name: "Expedition 6", spacecraft: "International Space Station", duration: "161 days, 1 hour, 14 minutes, 38 seconds", orbits: 2536, start_date: "November 25, 2002")
m05 = Mission.create(name: "Mir EO-18", spacecraft: nil, duration: nil, orbits: nil, start_date: nil)
m06 = Mission.create(name: "Mir EO-4 (Soyuz TM-7)", spacecraft: "Mir", duration: "151 days, 11 hours, 8 minutes", orbits: nil, start_date: "November 26, 1988")
m07 = Mission.create(name: "Mir LD-3 (Soyuz TM-12, Soyuz TM-13)", spacecraft: nil, duration: nil, orbits: nil, start_date: nil)
m08 = Mission.create(name: "Salyut 7-EP2 (Soyuz T-7 up, Soyuz T-5 down)", spacecraft: "Salyut-7", duration: nil, orbits: nil, start_date: nil)
m09 = Mission.create(name: "Salyut 7-EP4 (Soyuz T-12)", spacecraft: "Salyut-7", duration: nil, orbits: nil, start_date: nil)
m10 = Mission.create(name: "Soyuz 1", spacecraft: "Soyuz 7K-OK", duration: "1 day, 2 hours, 47 minutes, 52 seconds", orbits: 18, start_date: "April 23, 1967")
m11 = Mission.create(name: "Soyuz 19 (ASTP)", spacecraft: "Soyuz 19", duration: "5 days, 22 hours, 30 minutes", orbits: 96, start_date: "July 15, 1975")
m12 = Mission.create(name: "Soyuz 35/Soyuz 37", spacecraft: "Soyuz 7K-T", duration: "55 days, 1 hour, 28 minutes, 1 second", orbits: nil, start_date: "June 3, 1980")
m13 = Mission.create(name: "Soyuz 40", spacecraft: "Soyuz 7K-T", duration: "7 days, 20 hours, 41 minutes, 52 seconds", orbits: 124, start_date: "May 14, 1981")
m14 = Mission.create(name: "Soyuz T-7/Soyuz T-5", spacecraft: "Soyuz-T", duration: "113 days, 1 hour, 50 minutes, 44 seconds", orbits: 1825, start_date: "August 19, 1982")
m15 = Mission.create(name: "Soyuz T-7/Soyuz T-5", spacecraft: "Soyuz-T", duration: "113 days, 1 hour, 50 minutes, 44 seconds", orbits: 1825, start_date: "August 19, 1982")
m16 = Mission.create(name: "Soyuz T-8", spacecraft: "Soyuz-T", duration: "2 days, 17 minutes, 48 seconds", orbits: 32, start_date: "April 20, 1983")
m17 = Mission.create(name: "Soyuz TM-14", spacecraft: "Soyuz-TM", duration: "145 days, 14 hours, 10 minutes, 32 seconds", orbits: 2280, start_date: "March 17, 1992")
m18 = Mission.create(name: "Soyuz TM-17", spacecraft: "Soyuz-TM", duration: "196 days, 17 hours, 45 minutes, 22 seconds", orbits: 3070, start_date: "July 1, 1993")
m19 = Mission.create(name: "Soyuz TM-21", spacecraft: "Soyuz-TM", duration: "181 days, 41 minutes, 6 seconds", orbits: 2940, start_date: "March 14, 1995")
m20 = Mission.create(name: "Soyuz TM-24", spacecraft: "Soyuz-TM", duration: "196 days, 17 hours, 26 minutes, 13 seconds", orbits: 3160, start_date: "August 17, 1996")
m21 = Mission.create(name: "Soyuz TM-27", spacecraft: "Soyuz-TM", duration: "207 days, 12 hours, 51 minutes, 2 seconds", orbits: 3284, start_date: "January 29, 1998")
m22 = Mission.create(name: "Soyuz TM-28", spacecraft: "Soyuz-TM", duration: "198 days, 16 hours, 31 minutes, 19 seconds", orbits: 3144, start_date: "February 28, 1999")
m23 = Mission.create(name: "Soyuz TM-30", spacecraft: "Soyuz-TM", duration: "72 days, 19 hours, 42 minutes", orbits: 1145, start_date: "April 4, 2000")
m24 = Mission.create(name: "Soyuz TM-8", spacecraft: "Soyuz-TM", duration: "166 days, 6 hours, 58 minutes, 15 seconds", orbits: 2680, start_date: "September 5, 1989")
m25 = Mission.create(name: "Soyuz TMA-01M (Expedition 25/26)", spacecraft: "Soyuz-TMA 11F747", duration: nil, orbits: nil, start_date: "October 7, 2010")
m26 = Mission.create(name: "Soyuz TMA-04M (Expedition 31/32)", spacecraft: "Soyuz-TMA 11F747", duration: "4 months, 2 days", orbits: 1945, start_date: "May 15, 2012")
m27 = Mission.create(name: "Soyuz TMA-1", spacecraft: "Soyuz 11F732 No.211", duration: "185 days, 22 hours, 53 minutes, 14 seconds", orbits: 3020, start_date: "October 30, 2002")
m28 = Mission.create(name: "Soyuz TMA-13 (Expedition 18)", spacecraft: "Soyuz-TMA", duration: "178 days, 15 minutes", orbits: nil, start_date: "October 12, 2008")
m29 = Mission.create(name: "Soyuz TMA-14 (Expedition 19/20)", spacecraft: "Soyuz-TMA No.224", duration: "199 days", orbits: nil, start_date: "March 26, 2009")
m30 = Mission.create(name: "Soyuz TMA-16M (Expedition 43/44)", spacecraft: "Soyuz-TMA 11F732A47 No.716", duration: "168 days, 5 hours, 9 minutes", orbits: nil, start_date: "March 27, 2015")
m31 = Mission.create(name: "Soyuz TMA-3 (Expedition 8)", spacecraft: "Soyuz-TMA 11F732", duration: "194 days, 18 hours, 33 minutes, 12 seconds", orbits: 3170, start_date: "October 18, 2003")
m32 = Mission.create(name: "Soyuz TMA-4 (Expedition 9)", spacecraft: "Soyuz-TMA 11F732", duration: "187 days, 13 hours, 22 minutes", orbits: 2950, start_date: "April 19, 2004")
m33 = Mission.create(name: "Sputnik 2", spacecraft: "Sputnik 2", duration: "162 days", orbits: 2570, start_date: "November 3, 1957")
m34 = Mission.create(name: "STS-100", spacecraft: "Space Shuttle Endeavour", duration: "11 days, 21 hours, 31 minutes, 14 seconds", orbits: nil, start_date: "April 19, 2001")
m35 = Mission.create(name: "STS-105", spacecraft: "Space Shuttle Discovery", duration: "11 days, 21 hours, 13 minutes, 52 seconds", orbits: nil, start_date: "August 10, 2001")
m36 = Mission.create(name: "STS-108", spacecraft: "Space Shuttle Endeavour", duration: "11 days, 19 hours, 36 minutes, 45 seconds", orbits: nil, start_date: "December 5, 2001")
m37 = Mission.create(name: "STS-111", spacecraft: nil, duration: nil, orbits: nil, start_date: nil)
m38 = Mission.create(name: "STS-113", spacecraft: "Space Shuttle Endeavour", duration: "13 days, 18 hours, 48 minutes, 38 seconds", orbits: nil, start_date: "November 24, 2002")
m39 = Mission.create(name: "STS-60", spacecraft: "Space Shuttle Discovery", duration: "8 days, 7 hours, 9 minutes, 22 seconds", orbits: 130, start_date: "February 3, 1994")
m40 = Mission.create(name: "STS-71", spacecraft: "Space Shuttle Atlantis", duration: "9 days, 19 hours, 23 minutes, 9 seconds", orbits: 153, start_date: "June 27, 1995")
m41 = Mission.create(name: "STS-88", spacecraft: "Space Shuttle Endeavour", duration: "11 days, 19 hours, 18 minutes, 47 seconds", orbits: 186, start_date: "December 4, 1998")
m42 = Mission.create(name: "Voskhod 1", spacecraft: "Voskhod-3KV No.3", duration: "1 day, 17 minutes, 3 seconds", orbits: 16, start_date: "October 12, 1964")
m43 = Mission.create(name: "Voskhod 2", spacecraft: "Voskhod-3KD No.4", duration: "1 day, 2 hours, 2 minutes, 17 seconds", orbits: 17, start_date: "March 18, 1965")
m44 = Mission.create(name: "Vostok 1", spacecraft: "Vostok-3KA No.3", duration: "1 hour, 48 minutes", orbits: 1, start_date: nil)
m45 = Mission.create(name: "Vostok 6", spacecraft: nil, duration: nil, orbits: nil, start_date: nil)

CosmonautMission.create(cosmonaut_id:yg.id ,mission_id:m44.id)
CosmonautMission.create(cosmonaut_id:nb.id ,mission_id:m40.id)
CosmonautMission.create(cosmonaut_id:nb.id ,mission_id:m19.id)
CosmonautMission.create(cosmonaut_id:nb.id ,mission_id:m21.id)
CosmonautMission.create(cosmonaut_id:nb.id ,mission_id:m38.id)
CosmonautMission.create(cosmonaut_id:nb.id ,mission_id:m04.id)
CosmonautMission.create(cosmonaut_id:nb.id ,mission_id:m27.id)
CosmonautMission.create(cosmonaut_id:vd.id ,mission_id:m19.id)
CosmonautMission.create(cosmonaut_id:vd.id ,mission_id:m05.id)
CosmonautMission.create(cosmonaut_id:vd.id ,mission_id:m40.id)
CosmonautMission.create(cosmonaut_id:vd.id ,mission_id:m35.id)
CosmonautMission.create(cosmonaut_id:vd.id ,mission_id:m03.id)
CosmonautMission.create(cosmonaut_id:vd.id ,mission_id:m36.id)
CosmonautMission.create(cosmonaut_id:ak.id ,mission_id:m17.id)
CosmonautMission.create(cosmonaut_id:ak.id ,mission_id:m20.id)
CosmonautMission.create(cosmonaut_id:ak.id ,mission_id:m23.id)
CosmonautMission.create(cosmonaut_id:ak.id ,mission_id:m31.id)
CosmonautMission.create(cosmonaut_id:ak.id ,mission_id:m36.id)
CosmonautMission.create(cosmonaut_id:sk.id ,mission_id:m06.id)
CosmonautMission.create(cosmonaut_id:sk.id ,mission_id:m07.id)
CosmonautMission.create(cosmonaut_id:sk.id ,mission_id:m39.id)
CosmonautMission.create(cosmonaut_id:sk.id ,mission_id:m41.id)
CosmonautMission.create(cosmonaut_id:sk.id ,mission_id:m01.id)
CosmonautMission.create(cosmonaut_id:sk.id ,mission_id:m02.id)
CosmonautMission.create(cosmonaut_id:al.id ,mission_id:m43.id)
CosmonautMission.create(cosmonaut_id:al.id ,mission_id:m11.id)
CosmonautMission.create(cosmonaut_id:yl.id ,mission_id:m34.id)
CosmonautMission.create(cosmonaut_id:yl.id ,mission_id:m27.id)
CosmonautMission.create(cosmonaut_id:yl.id ,mission_id:m29.id)
CosmonautMission.create(cosmonaut_id:gp.id ,mission_id:m22.id)
CosmonautMission.create(cosmonaut_id:gp.id ,mission_id:m32.id)
CosmonautMission.create(cosmonaut_id:gp.id ,mission_id:m29.id)
CosmonautMission.create(cosmonaut_id:gp.id ,mission_id:m26.id)
CosmonautMission.create(cosmonaut_id:gp.id ,mission_id:m30.id)
CosmonautMission.create(cosmonaut_id:lp.id ,mission_id:m12.id)
CosmonautMission.create(cosmonaut_id:lp.id ,mission_id:m13.id)
CosmonautMission.create(cosmonaut_id:lp.id ,mission_id:m14.id)
CosmonautMission.create(cosmonaut_id:ss.id ,mission_id:m08.id)
CosmonautMission.create(cosmonaut_id:ss.id ,mission_id:m09.id)
CosmonautMission.create(cosmonaut_id:as.id ,mission_id:m14.id)
CosmonautMission.create(cosmonaut_id:as.id ,mission_id:m16.id)
CosmonautMission.create(cosmonaut_id:as.id ,mission_id:m24.id)
CosmonautMission.create(cosmonaut_id:as.id ,mission_id:m18.id)
CosmonautMission.create(cosmonaut_id:vt.id ,mission_id:m45.id)
CosmonautMission.create(cosmonaut_id:ag.id ,mission_id:m37.id)
CosmonautMission.create(cosmonaut_id:ag.id ,mission_id:m34.id)
CosmonautMission.create(cosmonaut_id:ag.id ,mission_id:m35.id)
CosmonautMission.create(cosmonaut_id:ag.id ,mission_id:m36.id)
CosmonautMission.create(cosmonaut_id:ag.id ,mission_id:m38.id)
CosmonautMission.create(cosmonaut_id:l.id ,mission_id:m33.id)
CosmonautMission.create(cosmonaut_id:vk.id ,mission_id:m42.id)
CosmonautMission.create(cosmonaut_id:vk.id ,mission_id:m10.id)

